import {
  BarChart,
  Button,
  Callout,
  Card,
  CardBody,
  CardHeader,
  Divider,
  Grid,
  H1,
  H2,
  IconButton,
  Pill,
  Row,
  Spacer,
  Stack,
  Stat,
  Table,
  Text,
  UsageBar,
  useState,
} from "cursor/canvas";

// Auto-generated by scripts/build_screen_dashboard.py — do not edit by hand.
const RUN = {
  asOf: "2026-09-22",
  vix: 14.19,
  regime: "risk",
  cape: 41.6,
  buffett: 276,
  cycle: "expensive",
  universe: 80,
  support: 45,
  catalyst: 75,
  fund: 20,
  pol: 279,
  trumpPosts: 366,
  trumpTickers: 67,
  athdipPass: 6,
  athdipLowestRsi4h: 18.2,
  spyYtd: 12.71,
  note: "Generated from output/screen_*.csv · watchlist only, not advice",
};

const FOCUS = [
  {kind:"conflict",ticker:"ALL",signal:"MIXED",price:229.3,tags:"athdip \u00b7 support \u00b7 catalyst \u00b7 fundamentals \u00b7 politicians",why:"Athdip dip vs Congress sells (0/1) \u00b7 trigger today (2026-09-22)",athdip:51.5,support:84.9,catalyst:56.6,fund:71.6,pol:42.0,trump:null,rsi14:27.0,rsi4h:18.2,sector:"Financial Services",pe:4.6,peg:1.79,fcfy:26.2,roe:46.1},
  {kind:"athdip",ticker:"BAC",signal:"BUY",price:56.48,tags:"athdip \u00b7 trump",why:"Athdip \u00b7 trigger today (2026-09-22)",athdip:49.7,support:null,catalyst:null,fund:null,pol:null,trump:70.7,rsi14:26.5,rsi4h:22.0,sector:"",pe:13.1,peg:0.87,fcfy:null,roe:11.2},
  {kind:"intersection",ticker:"AMP",signal:"BUY",price:514.9,tags:"athdip \u00b7 support \u00b7 catalyst \u00b7 fundamentals",why:"Athdip + multi-mode overlap \u00b7 trigger today (2026-09-22)",athdip:49.5,support:71.7,catalyst:45.0,fund:70.5,pol:null,trump:null,rsi14:31.3,rsi4h:22.4,sector:"Financial Services",pe:12.5,peg:1.51,fcfy:6.4,roe:63.4},
  {kind:"intersection",ticker:"AEE",signal:"BUY",price:101.69,tags:"athdip \u00b7 support \u00b7 catalyst \u00b7 fundamentals",why:"Athdip + multi-mode overlap \u00b7 trigger today (2026-09-22)",athdip:30.7,support:73.3,catalyst:52.8,fund:52.0,pol:null,trump:null,rsi14:30.6,rsi4h:29.3,sector:"Utilities",pe:17.9,peg:2.51,fcfy:-6.3,roe:11.9},
  {kind:"single",ticker:"AFL",signal:"MIXED",price:114.59,tags:"support \u00b7 catalyst \u00b7 fundamentals \u00b7 politicians",why:"Top support score today",athdip:null,support:87.5,catalyst:61.6,fund:66.0,pol:42.8,trump:null,rsi14:38.7,rsi4h:null,sector:"Financial Services",pe:12.4,peg:1.18,fcfy:9.0,roe:16.9},
  {kind:"single",ticker:"AZO",signal:"MIXED",price:2934.51,tags:"support \u00b7 catalyst \u00b7 politicians",why:"Top catalyst score today",athdip:null,support:58.1,catalyst:81.7,fund:null,pol:39.9,trump:null,rsi14:49.9,rsi4h:null,sector:"",pe:20.2,peg:1.27,fcfy:null,roe:null},
  {kind:"single",ticker:"LMT",signal:"BUY",price:521.55,tags:"trump",why:"Top Trump tracker",athdip:null,support:null,catalyst:null,fund:null,pol:null,trump:100.0,rsi14:null,rsi4h:null,sector:"",pe:19.2,peg:1.01,fcfy:4.6,roe:89.2},
  {kind:"single",ticker:"CHWY",signal:"BUY",price:19.77,tags:"politicians",why:"Top politicians \u00b7 buys=4 sells=0",athdip:null,support:null,catalyst:null,fund:null,pol:78.7,trump:null,rsi14:null,rsi4h:null,sector:"",pe:30.4,peg:0.42,fcfy:5.7,roe:72.0}
];

const ATHDIP = [
  {ticker:"ALL",price:229.3,ath:276.07,pctAth:-16.94,days:38,rsi4h:18.2,rsiD:27.0,score:51.47},
  {ticker:"BAC",price:56.48,ath:64.9,pctAth:-12.97,days:25,rsi4h:22.0,rsiD:26.5,score:49.71},
  {ticker:"AMP",price:514.9,ath:572.56,pctAth:-10.07,days:26,rsi4h:22.4,rsiD:31.3,score:49.45},
  {ticker:"AMGN",price:409.93,ath:447.03,pctAth:-8.3,days:19,rsi4h:29.7,rsiD:54.3,score:39.14},
  {ticker:"AEE",price:101.69,ath:117.49,pctAth:-13.45,days:60,rsi4h:29.3,rsiD:30.6,score:30.7},
  {ticker:"AMAT",price:471.15,ath:738.88,pctAth:-36.23,days:58,rsi4h:30.2,rsiD:51.7,score:23.43}
];

const BACKTEST_YTD = [
  {mode:"trump*",ret:60.68,excess:47.97,win:58.3,dd:-11.8,avg:10.0},
  {mode:"athdip\u2020",ret:39.57,excess:26.85,win:22.4,dd:-11.56,avg:0.7},
  {mode:"catalyst",ret:16.5,excess:3.79,win:50.0,dd:-7.23,avg:9.0},
  {mode:"support",ret:16.1,excess:3.39,win:52.8,dd:-7.58,avg:10.0},
  {mode:"value",ret:1.36,excess:-11.35,win:61.1,dd:-16.7,avg:7.0},
  {mode:"SPY",ret:12.71,excess:0.0,win:0.0,dd:0.0,avg:1.0}
];

const TRUMP_SOURCES = [
  { label: "Truth Social", count: 80 },
  { label: "Google News", count: 230 },
  { label: "White House", count: 56 },
];

const TRUMP = [
  {ticker:"LMT",score:100.0,mentions:58,themes:"company, defense, govt_equity",sources:"news, truth, WH"},
  {ticker:"BA",score:98.76,mentions:56,themes:"defense, tariffs_trade",sources:"news, truth, WH"},
  {ticker:"INTC",score:97.9,mentions:79,themes:"company, govt_equity, semis_tech",sources:"news, truth, WH"},
  {ticker:"NVDA",score:94.73,mentions:66,themes:"china, company, govt_equity, semis_tech",sources:"news, truth, WH"},
  {ticker:"AAPL",score:82.82,mentions:45,themes:"china, company, tariffs_trade",sources:"news, truth, WH"},
  {ticker:"GD",score:80.7,mentions:33,themes:"defense",sources:"news, truth, WH"},
  {ticker:"NOC",score:80.7,mentions:33,themes:"defense",sources:"news, truth, WH"},
  {ticker:"RTX",score:80.7,mentions:33,themes:"defense",sources:"news, truth, WH"},
  {ticker:"XAR",score:80.7,mentions:33,themes:"defense",sources:"news, truth, WH"},
  {ticker:"COIN",score:71.57,mentions:28,themes:"banks_finance, company",sources:"news, truth, WH"}
];

const SUPPORT = [
  {ticker:"AFL",price:114.59,rsi:38.67,rsiBias:"toward oversold",rsiSlope:-6.94,prox:0.062,pct52h:-11.56,peg:1.18,fcfy:0.0897,roe:0.169,score:87.48},
  {ticker:"UNH",price:373.99,rsi:36.9,rsiBias:"neutral",rsiSlope:-0.02,prox:0.018,pct52h:-18.48,peg:1.024,fcfy:0.0723,roe:0.142,score:86.69},
  {ticker:"ALL",price:229.3,rsi:26.98,rsiBias:"oversold",rsiSlope:-17.71,prox:0.0,pct52h:-16.94,peg:1.786,fcfy:0.2616,roe:0.461,score:84.87},
  {ticker:"AIZ",price:275.14,rsi:39.34,rsiBias:"toward oversold",rsiSlope:-12.75,prox:0.182,pct52h:-9.2,peg:2.16,fcfy:0.1585,roe:0.183,score:79.13},
  {ticker:"JPM",price:340.72,rsi:35.97,rsiBias:"toward oversold",rsiSlope:-7.95,prox:0.367,pct52h:-7.03,peg:1.637,fcfy:null,roe:0.178,score:78.17},
  {ticker:"BALL",price:60.16,rsi:40.46,rsiBias:"neutral",rsiSlope:-1.77,prox:0.103,pct52h:-11.03,peg:1.006,fcfy:0.0239,roe:0.172,score:78.17},
  {ticker:"BAX",price:23.67,rsi:40.89,rsiBias:"toward overbought",rsiSlope:10.77,prox:0.286,pct52h:-21.05,peg:36.68,fcfy:0.0817,roe:-0.144,score:77.19},
  {ticker:"AON",price:286.42,rsi:26.27,rsiBias:"oversold",rsiSlope:-3.63,prox:0.0,pct52h:-24.92,peg:2.281,fcfy:0.0525,roe:0.447,score:75.99}
];

const CATALYST = [
  {ticker:"AZO",price:2934.51,rsi:49.86,rsiBias:"toward overbought",rsiSlope:11.24,day:4.68,vol:1.71,pct52h:-32.27,score:81.67},
  {ticker:"AMD",price:621.32,rsi:73.61,rsiBias:"overbought",rsiSlope:10.83,day:0.94,vol:1.04,pct52h:-0.15,score:77.45},
  {ticker:"ABBV",price:265.74,rsi:61.14,rsiBias:"toward overbought",rsiSlope:2.05,day:0.48,vol:0.35,pct52h:-0.64,score:74.68},
  {ticker:"ADI",price:389.14,rsi:62.31,rsiBias:"toward overbought",rsiSlope:16.19,day:1.6,vol:0.42,pct52h:-12.47,score:73.8},
  {ticker:"AAPL",price:340.41,rsi:67.39,rsiBias:"neutral",rsiSlope:1.95,day:0.42,vol:0.64,pct52h:-1.43,score:73.41},
  {ticker:"BE",price:274.3,rsi:59.99,rsiBias:"toward oversold",rsiSlope:-3.82,day:0.52,vol:0.53,pct52h:-21.91,score:72.67},
  {ticker:"MSFT",price:498.92,rsi:55.51,rsiBias:"neutral",rsiSlope:-0.21,day:-0.54,vol:0.69,pct52h:-9.15,score:72.12},
  {ticker:"ACN",price:184.93,rsi:52.28,rsiBias:"toward oversold",rsiSlope:-5.9,day:-0.64,vol:0.54,pct52h:-35.16,score:71.87}
];

const POLITICIANS = [
  {ticker:"CHWY",score:78.74,buys:4,sells:0,filedAfter:25.0,pols:"Ro Khanna",sources:"capitoltrades"},
  {ticker:"BSX",score:78.33,buys:4,sells:0,filedAfter:25.5,pols:"Gil Cisneros, Gilbert Cisneros, Ro Khanna",sources:"capitoltrades,house"},
  {ticker:"MRVL",score:75.45,buys:4,sells:0,filedAfter:31.8,pols:"Gilbert Cisneros, Ro Khanna",sources:"capitoltrades,house"},
  {ticker:"PWR",score:74.26,buys:3,sells:0,filedAfter:23.0,pols:"Gil Cisneros, Gilbert Cisneros, Ro Khanna",sources:"capitoltrades,house"},
  {ticker:"LOW",score:72.99,buys:3,sells:0,filedAfter:22.7,pols:"Ro Khanna",sources:"capitoltrades"},
  {ticker:"LEN",score:72.99,buys:3,sells:0,filedAfter:22.7,pols:"Ro Khanna",sources:"capitoltrades"},
  {ticker:"MCHP",score:72.8,buys:3,sells:0,filedAfter:27.3,pols:"Ro Khanna",sources:"capitoltrades"},
  {ticker:"COO",score:72.37,buys:2,sells:0,filedAfter:5.5,pols:"Ro Khanna",sources:"capitoltrades"}
];

const FUNDAMENTALS = [
  {ticker:"AMAT",sector:"Technology",peg:0.92,fcfy:0.0082,roe:0.411,score:74.86},
  {ticker:"LLY",sector:"Healthcare",peg:1.15,fcfy:0.0106,roe:1.023,score:72.04},
  {ticker:"ALL",sector:"Financial Services",peg:1.79,fcfy:0.2616,roe:0.461,score:71.58},
  {ticker:"AMP",sector:"Financial Services",peg:1.51,fcfy:0.0638,roe:0.634,score:70.5},
  {ticker:"BRK-B",sector:"Financial Services",peg:10.06,fcfy:0.0667,roe:0.121,score:70.1},
  {ticker:"JPM",sector:"Financial Services",peg:1.64,fcfy:null,roe:0.178,score:68.62},
  {ticker:"AMCR",sector:"Consumer Cyclical",peg:0.96,fcfy:0.0752,roe:0.094,score:67.66},
  {ticker:"BEN",sector:"Financial Services",peg:0.42,fcfy:-0.1768,roe:0.079,score:67.4}
];

function biasTone(bias: string): "success" | "warning" | "danger" | "info" | "neutral" {
  if (bias === "oversold" || bias === "toward oversold") return "success";
  if (bias === "overbought" || bias === "toward overbought") return "warning";
  return "neutral";
}

function focusTone(kind: string): "success" | "warning" | "danger" | "info" | "neutral" {
  if (kind === "conflict") return "danger";
  if (kind === "intersection" || kind === "confirm" || kind === "athdip") return "success";
  if (kind === "single") return "info";
  return "neutral";
}

function dash(n: number | null | undefined, digits = 1): string {
  if (n === null || n === undefined || Number.isNaN(n)) return "—";
  return n.toFixed(digits);
}

function polTone(buys: number, sells: number): "success" | "warning" | "danger" | "info" | "neutral" {
  if (buys > sells) return "success";
  if (sells > buys) return "warning";
  return "neutral";
}

function trumpTone(score: number): "success" | "warning" | "info" | "neutral" {
  if (score >= 85) return "success";
  if (score >= 70) return "info";
  return "neutral";
}

function formatBias(bias: string, slope: number): string {
  const arrow = slope < -2 ? " ↓" : slope > 2 ? " ↑" : "";
  return `${bias}${arrow}`;
}

function pct(x: number): string {
  return `${(x * 100).toFixed(1)}%`;
}

/** Click ? to reveal the definition in the tip Callout (canvas has no browser hover tooltips). */
function signalTone(sig: string): "success" | "warning" | "danger" | "info" | "neutral" {
  if (sig === "BUY") return "success";
  if (sig === "SELL") return "danger";
  if (sig === "MIXED") return "warning";
  return "neutral";
}

export default function ScreenDashboard() {
  const [tip, setTip] = useState<string | null>(null);
  const showTip = (label: string, text: string) => setTip(`${label} — ${text}`);

  function th(label: string, tipText: string) {
    return (
      <Row gap={4} align="center">
        <span>{label}</span>
        <IconButton
          size="sm"
          title={tipText}
          onClick={() => showTip(label, tipText)}
        >
          ?
        </IconButton>
      </Row>
    );
  }

  function withTip(label: string, tipText: string, node: JSX.Element) {
    return (
      <Stack gap={4}>
        <div
          onClick={() => showTip(label, tipText)}
          style={{ cursor: "pointer" }}
          title={tipText}
        >
          {node}
        </div>
        <IconButton
          size="sm"
          title={tipText}
          onClick={() => showTip(label, tipText)}
        >
          ?
        </IconButton>
      </Stack>
    );
  }

  const srcTotal = TRUMP_SOURCES.reduce((a, s) => a + s.count, 0);
  const cross = FOCUS.filter((r) => r.kind !== "single");
  const singles = FOCUS.filter((r) => r.kind === "single");

  const crossHeaders = [
    th(
      "Kind",
      "Row type: conflict means modes disagree; intersection means modes agree; athdip or confirm means setup-driven signals",
    ),
    th("Ticker", "Stock ticker symbol"),
    th(
      "Signal",
      "Watchlist lean for this long-only screener: BUY = long setup; SELL = Congress sell-flow dominates without other long modes; MIXED = conflict (for example athdip vs Congress sells)",
    ),
    th(
      "Price",
      "Latest screen price (usually prior session close or last available quote)",
    ),
    th("RSI", "Daily fourteen-period relative strength index when available"),
    th("Why", "Reason this name was selected for the Today list"),
    th("Modes", "Which screener modes tagged this ticker"),
    th(
      "Ath",
      "Athdip-mode composite score (higher means deeper four-hour relative strength index and a fresher all-time-high setup)",
    ),
    th("Sup", "Support-mode composite score"),
    th(
      "Cat",
      "Catalyst-mode composite score (Yahoo news ± X-quoting headlines ± Polymarket ± 13F social)",
    ),
    th("Fund", "Fundamentals-mode composite score"),
    th(
      "Pol",
      "Politicians-mode score based on freshness-weighted United States Congress trading flow",
    ),
    th("Trump", "Trump-tracker theme score from Truth Social, news, and White House feeds"),
    th("Sector", "Company sector classification from Yahoo Finance"),
    th("PE", "Trailing price-to-earnings ratio"),
    th(
      "PEG",
      "Price/earnings-to-growth ratio (lower often means cheaper relative to expected growth)",
    ),
    th("FCF%", "Free-cash-flow yield as a percent of market value"),
    th("ROE%", "Return on equity as a percent"),
  ];
  const singleHeaders = [
    th("Mode", "Primary single-mode leader category"),
    th("Ticker", "Stock ticker symbol"),
    th(
      "Signal",
      "Watchlist lean: BUY = long setup; SELL = Congress sell-flow dominates; MIXED = conflicting modes",
    ),
    th(
      "Price",
      "Latest screen price (usually prior session close or last available quote)",
    ),
    th("RSI", "Daily fourteen-period relative strength index when available"),
    th("Why", "Reason this name is listed as a single-mode leader"),
    th("Lead", "Composite or mode score in the leading category"),
    th("Sector", "Company sector classification from Yahoo Finance"),
    th("PE", "Trailing price-to-earnings ratio"),
    th("PEG", "Price/earnings-to-growth ratio"),
    th("FCF%", "Free-cash-flow yield as a percent of market value"),
    th("ROE%", "Return on equity as a percent"),
  ];

  return (
    <Stack gap={28} style={{ maxWidth: 1100 }}>
      <Stack gap={8}>
        <H1>Screener dashboard</H1>
        <Text tone="secondary">
          All modes · SP500/{RUN.universe} · {RUN.asOf}
        </Text>
        <Text tone="secondary" style={{ fontSize: 12 }}>
          Click any ? to show that column or metric definition below (canvas does not show browser hover tooltips).
        </Text>
        {tip ? (
          <Callout tone="info" title="Definition">
            <Stack gap={8}>
              <Text>{tip}</Text>
              <Button variant="secondary" onClick={() => setTip(null)}>
                Dismiss
              </Button>
            </Stack>
          </Callout>
        ) : null}
      </Stack>

      <Grid columns={4} gap={12}>
        {withTip(
          "VIX",
          "CBOE Volatility Index (^VIX) — market fear gauge. Risk-on at or below about 15; risk-off at or above about 25; mid range is neutral.",
          <Stat value={RUN.vix.toFixed(1)} label="VIX" />,
        )}
        {withTip(
          "Regime",
          "VIX-driven trading regime (risk-on / neutral / risk-off). Tightens or loosens support and catalyst filters and weights.",
          <Stat value={RUN.regime} label="Regime" tone="info" />,
        )}
        {withTip(
          "CAPE",
          "Shiller CAPE (cyclically adjusted price-to-earnings). Rough bands: under 20 cheap, 20–28 fair, over 28 expensive. Used with Buffett for the market-cycle label.",
          <Stat value={String(RUN.cape)} label="CAPE" tone="warning" />,
        )}
        {withTip(
          "Buffett",
          "Buffett Indicator ≈ total US equity market cap / GDP (percent). Rough bands: under 100% cheap, 100–140% fair, over 140% expensive. Label after the · is the combined cycle read with CAPE.",
          <Stat value={`${RUN.buffett}%`} label={`Buffett · ${RUN.cycle}`} tone="warning" />,
        )}
      </Grid>

      <Grid columns={6} gap={10}>
        {withTip(
          "Support",
          "Count of names that passed Support-mode filters in this screen run (near support / mean-reversion).",
          <Stat value={String(RUN.support)} label="Support" />,
        )}
        {withTip(
          "Catalyst",
          "Count of names that passed Catalyst-mode filters (news / earnings / momentum; social may include Polymarket).",
          <Stat value={String(RUN.catalyst)} label="Catalyst" />,
        )}
        {withTip(
          "Fundamentals",
          "Count of Fundamentals-mode leaders (growth, profitability, balance sheet, ROIC, valuation).",
          <Stat value={String(RUN.fund)} label="Fundamentals" />,
        )}
        {withTip(
          "Politicians",
          "Count of tickers with freshness-weighted United States Congress trading flow in Politicians mode.",
          <Stat value={String(RUN.pol)} label="Politicians" />,
        )}
        {withTip(
          "Trump",
          "Count of tickers mapped from Trump-tracker themes (Truth Social, Google News, White House feeds).",
          <Stat value={String(RUN.trumpTickers)} label="Trump" tone="info" />,
        )}
        {withTip(
          "Athdip",
          "Count of Athdip hard passes: recent multi-year all-time-high setup with four-hour relative strength index near oversold.",
          <Stat value={String(RUN.athdipPass)} label="Athdip" tone="success" />,
        )}
      </Grid>

      <Callout tone="info" title={RUN.note}>
        Rebuild: python3 scripts/build_screen_dashboard.py
      </Callout>

      <Stack gap={10}>
        <Row align="center" gap={10}>
          {withTip(
            "Today",
            "Cross-mode intersections, conflicts, and single-mode leaders with fundamentals",
            <H2>Today</H2>,
          )}
          <Pill
            tone="warning"
            title="Informational watchlist only — not investment advice"
            onClick={() =>
              showTip(
                "Watchlist",
                "Informational watchlist only — not investment advice",
              )
            }
          >
            watchlist · not advice
          </Pill>
        </Row>
        <Text tone="secondary">
          Intersections / conflicts first, then top single-mode leaders — with fundamentals.
        </Text>

        {withTip(
          "Cross-mode",
          "Names tagged by more than one mode, or where modes disagree",
          <Text weight="semibold">Cross-mode intersections & conflicts</Text>,
        )}
        <Table
          headers={crossHeaders}
          columnAlign={["left","left","left","right","right","left","left","right","right","right","right","right","right","left","right","right","right","right"]}
          rows={cross.map((r) => [
            r.kind,
            r.ticker,
            r.signal || "BUY",
            dash(r.price, 2),
            dash(r.rsi14),
            r.why,
            r.tags,
            dash(r.athdip),
            dash(r.support),
            dash(r.catalyst),
            dash(r.fund),
            dash(r.pol),
            dash(r.trump),
            r.sector || "—",
            dash(r.pe),
            dash(r.peg, 2),
            dash(r.fcfy),
            dash(r.roe),
          ])}
          rowTone={cross.map((r) => signalTone(r.signal || "BUY"))}
        />

        {withTip(
          "Single-mode",
          "Top names that only lead in a single mode (not already listed in the cross-mode section)",
          <Text weight="semibold">Single-mode leaders</Text>,
        )}
        <Table
          headers={singleHeaders}
          columnAlign={["left","left","left","right","right","left","right","left","right","right","right","right"]}
          rows={singles.map((r) => {
            const lead = r.support ?? r.catalyst ?? r.trump ?? r.pol ?? r.fund ?? null;
            return [
              r.tags.split(" · ")[0] || r.tags,
              r.ticker,
              r.signal || "BUY",
              dash(r.price, 2),
              dash(r.rsi14),
              r.why,
              dash(lead),
              r.sector || "—",
              dash(r.pe),
              dash(r.peg, 2),
              dash(r.fcfy),
              dash(r.roe),
            ];
          })}
          rowTone={singles.map((r) => signalTone(r.signal || "BUY"))}
        />
        <Text tone="secondary" style={{ fontSize: 12 }}>
          Source: output/today_focus.csv · {RUN.asOf}
        </Text>
      </Stack>

      <Divider />

      <Stack gap={10}>
        <Row align="center" gap={10}>
          {withTip(
            "Athdip",
            "Uptrend near a multi-year all-time high with a four-hour relative strength index dip near oversold",
            <H2>Athdip</H2>,
          )}
          <Pill
            tone="success"
            title="Requires a recent multi-year ATH setup plus four-hour RSI near about 30"
            onClick={() =>
              showTip(
                "Athdip filter",
                "Requires a recent multi-year ATH setup plus four-hour RSI near about 30",
              )
            }
          >
            ATH setup + 4h RSI dip
          </Pill>
        </Row>
        <Table
          headers={[
            th("Ticker", "Stock ticker symbol"),
            th("Price", "Latest screen price (usually prior session close or last available quote)"),
            th("ATH", "Multi-year all-time high used for the athdip setup"),
            th("%ATH", "Percent below the all-time high (more negative means a deeper pullback)"),
            th("Days", "Trading days since the multi-year all-time high"),
            th("RSI 4h", "Minimum four-hour relative strength index over the lookback window (trigger when at or below about 31)"),
            th("RSI D", "Daily fourteen-period relative strength index"),
            th("Score", "Athdip-mode composite score"),
          ]}
          columnAlign={["left","right","right","right","right","right","right","right"]}
          rows={ATHDIP.map((r) => [
            r.ticker,
            dash(r.price, 2),
            dash(r.ath, 2),
            `${dash(r.pctAth)}%`,
            String(r.days),
            dash(r.rsi4h),
            dash(r.rsiD),
            dash(r.score),
          ])}
        />
      </Stack>

      <Divider />

      <Stack gap={10}>
        <Row align="center" gap={10}>
          {withTip(
            "Trump tracker",
            "Maps Truth Social, Google News, and White House items to liquid tickers by cashtag, company name, and policy theme",
            <H2>Trump tracker</H2>,
          )}
          <Pill
            tone="warning"
            title="Freshness-weighted theme scores — not a trading signal by itself"
            onClick={() =>
              showTip(
                "Trump themes",
                "Freshness-weighted theme scores — not a trading signal by itself",
              )
            }
          >
            policy / themes
          </Pill>
        </Row>
        {withTip(
          "Feed mix",
          "Share of Trump-tracker items by source: Truth Social mirror, Google News RSS, and White House RSS",
          <UsageBar
            total={srcTotal || 1}
            segments={TRUMP_SOURCES.map((s) => ({ id: s.label, value: s.count }))}
            topLeftLabel="Feed mix"
            topRightLabel={`${srcTotal} items`}
          />,
        )}
        <BarChart
          categories={TRUMP.slice(0, 10).map((r) => r.ticker)}
          series={[{ name: "Trump score", data: TRUMP.slice(0, 10).map((r) => r.score), tone: "warning" }]}
          height={200}
        />
        <Table
          headers={[
            th("Ticker", "Stock ticker symbol"),
            th("Score", "Trump-tracker theme score from Truth Social, news, and White House feeds"),
            th("Mentions", "Count of matched posts or headlines mapped to this ticker"),
            th("Themes", "Policy or company themes that triggered the mapping"),
          ]}
          columnAlign={["left","right","right","left"]}
          rows={TRUMP.map((r) => [r.ticker, dash(r.score), String(r.mentions), r.themes])}
          rowTone={TRUMP.map((r) => trumpTone(r.score))}
        />
      </Stack>

      <Divider />

      <Stack gap={10}>
        {withTip(
          "YTD backtest",
          "Year-to-date paper returns by mode versus SPY (from the optional backtest script)",
          <H2>YTD backtest</H2>,
        )}
        <BarChart
          categories={BACKTEST_YTD.map((r) => r.mode)}
          series={[{ name: "YTD return %", data: BACKTEST_YTD.map((r) => r.ret), tone: "info" }]}
          height={200}
        />
        <Table
          headers={[
            th("Mode", "Backtest mode or strategy label"),
            th("Return %", "Year-to-date strategy return in percent"),
            th("Excess %", "Strategy return minus SPY over the same window"),
            th("Win %", "Share of rebalance periods with a positive return"),
            th("Max DD %", "Maximum peak-to-trough drawdown in percent"),
            th("Avg #", "Average number of holdings per rebalance"),
          ]}
          columnAlign={["left","right","right","right","right","right"]}
          rows={BACKTEST_YTD.map((r) => [
            r.mode,
            dash(r.ret, 2),
            dash(r.excess, 2),
            dash(r.win, 1),
            dash(r.dd, 2),
            dash(r.avg, 1),
          ])}
        />
      </Stack>

      <Divider />

      <Stack gap={10}>
        {withTip(
          "Politicians",
          "United States Congress STOCK Act disclosures (Capitol Trades plus House/Senate), freshness-weighted",
          <H2>Politicians</H2>,
        )}
        <Table
          headers={[
            th("Ticker", "Stock ticker symbol"),
            th("Score", "Politicians-mode score from freshness-weighted United States Congress trading flow"),
            th("Buys", "Count of buy-side disclosures in the lookback"),
            th("Sells", "Count of sell-side disclosures in the lookback"),
            th("Filed after", "Average days between trade and filing (lower is fresher)"),
            th("Politicians", "Lawmakers associated with the matched trades"),
          ]}
          columnAlign={["left","right","right","right","right","left"]}
          rows={POLITICIANS.map((r) => [
            r.ticker,
            dash(r.score),
            String(r.buys),
            String(r.sells),
            dash(r.filedAfter),
            r.pols,
          ])}
          rowTone={POLITICIANS.map((r) => polTone(r.buys, r.sells))}
        />
      </Stack>

      <Divider />

      <Stack gap={10}>
        {withTip(
          "Support",
          "Near support or SMA pullback setups with VIX-regime gates",
          <H2>Support</H2>,
        )}
        <Table
          headers={[
            th("Ticker", "Stock ticker symbol"),
            th("Price", "Latest screen price"),
            th("RSI", "Daily fourteen-period relative strength index"),
            th("Bias", "Whether RSI is bending toward oversold or overbought (arrow shows slope)"),
            th("Prox", "Proximity to support versus resistance (lower means closer to support)"),
            th("%52wH", "Percent from the fifty-two-week high"),
            th("PEG", "Price/earnings-to-growth ratio"),
            th("FCF", "Free-cash-flow yield"),
            th("ROE", "Return on equity"),
            th("Score", "Support-mode composite score"),
          ]}
          columnAlign={["left","right","right","left","right","right","right","right","right","right"]}
          rows={SUPPORT.map((r) => [
            r.ticker,
            dash(r.price, 2),
            dash(r.rsi),
            formatBias(r.rsiBias, r.rsiSlope ?? 0),
            dash(r.prox, 3),
            `${dash(r.pct52h)}%`,
            dash(r.peg, 2),
            r.fcfy == null ? "—" : pct(r.fcfy),
            r.roe == null ? "—" : pct(r.roe),
            dash(r.score, 2),
          ])}
          rowTone={SUPPORT.map((r) => biasTone(r.rsiBias))}
        />
      </Stack>

      <Divider />

      <Stack gap={10}>
        {withTip(
          "Catalyst",
          "News, earnings proximity, and momentum pops; social may include Polymarket odds",
          <H2>Catalyst</H2>,
        )}
        <Table
          headers={[
            th("Ticker", "Stock ticker symbol"),
            th("Price", "Latest screen price"),
            th("RSI", "Daily fourteen-period relative strength index"),
            th("Bias", "Whether RSI is bending toward oversold or overbought (arrow shows slope)"),
            th("Day %", "One-day percent price change"),
            th("Vol×", "Volume versus recent average (above about 1.4 often counts as a catalyst signal)"),
            th("%52wH", "Percent from the fifty-two-week high"),
            th("Score", "Catalyst-mode composite (includes Yahoo news ± X-quoting headlines ± Polymarket social)"),
          ]}
          columnAlign={["left","right","right","left","right","right","right","right"]}
          rows={CATALYST.map((r) => [
            r.ticker,
            dash(r.price, 2),
            dash(r.rsi),
            formatBias(r.rsiBias, r.rsiSlope ?? 0),
            dash(r.day, 2),
            dash(r.vol, 2),
            `${dash(r.pct52h)}%`,
            dash(r.score, 2),
          ])}
          rowTone={CATALYST.map((r) => biasTone(r.rsiBias))}
        />
      </Stack>

      <Divider />

      <Stack gap={10}>
        {withTip(
          "Fundamentals",
          "Growth, profitability, balance sheet, capital efficiency, and valuation composite",
          <H2>Fundamentals</H2>,
        )}
        <Table
          headers={[
            th("Ticker", "Stock ticker symbol"),
            th("Sector", "Company sector classification from Yahoo Finance"),
            th("PEG", "Price/earnings-to-growth ratio (lower often means cheaper relative to expected growth)"),
            th("FCF yld", "Free-cash-flow yield"),
            th("ROE", "Return on equity"),
            th("Score", "Fundamentals-mode composite score"),
          ]}
          columnAlign={["left","left","right","right","right","right"]}
          rows={FUNDAMENTALS.map((r) => [
            r.ticker,
            r.sector,
            dash(r.peg, 2),
            r.fcfy == null ? "—" : pct(r.fcfy),
            r.roe == null ? "—" : pct(r.roe),
            dash(r.score, 2),
          ])}
        />
      </Stack>

      <Card>
        <CardHeader>Reproduce</CardHeader>
        <CardBody>
          <Stack gap={6}>
            <Text style={{ fontFamily: "monospace", fontSize: 12 }}>
              stock-screener --mode all --universe sp500 --limit 80 --no-reddit --no-grok --no-trump-x
            </Text>
            <Text style={{ fontFamily: "monospace", fontSize: 12 }}>
              python3 scripts/build_screen_dashboard.py
            </Text>
            <Spacer height={4} />
            <Text tone="secondary" style={{ fontSize: 13 }}>
              Project skill: .cursor/skills/daily-screen
            </Text>
          </Stack>
        </CardBody>
      </Card>
    </Stack>
  );
}
