import {
  BarChart,
  Callout,
  Card,
  CardBody,
  CardHeader,
  Divider,
  Grid,
  H1,
  H2,
  Pill,
  Row,
  Spacer,
  Stack,
  Stat,
  Table,
  Text,
  UsageBar,
} from "cursor/canvas";

// Auto-generated by scripts/build_screen_dashboard.py — do not edit by hand.
const RUN = {
  asOf: "2026-09-09",
  vix: 16.18,
  regime: "neutral",
  cape: 41.2,
  buffett: 274,
  universe: 80,
  support: 32,
  catalyst: 68,
  fund: 19,
  pol: 238,
  trumpPosts: 372,
  trumpTickers: 69,
  athdipPass: 2,
  athdipLowestRsi4h: 23.5,
  spyYtd: 12.71,
  note: "Generated from output/screen_*.csv · watchlist only, not advice",
};

const FOCUS = [
  {kind:"conflict",ticker:"AMGN",price:391.27,tags:"athdip \u00b7 politicians",why:"Athdip dip vs Congress sells (0/3) \u00b7 px 391.27 < trigger 393.17 (2026-09-08)",athdip:52.1,support:null,catalyst:null,fund:null,pol:37.6,trump:null,rsi4h:23.5,sector:"",pe:24.3,peg:2.11,fcfy:4.1,roe:91.5},
  {kind:"intersection",ticker:"ADI",price:364.05,tags:"support \u00b7 catalyst \u00b7 fundamentals",why:"Support+fund confirm",athdip:null,support:78.0,catalyst:62.0,fund:73.1,pol:null,trump:null,rsi4h:null,sector:"Technology",pe:43.2,peg:0.54,fcfy:2.4,roe:12.2},
  {kind:"intersection",ticker:"AMAT",price:469.87,tags:"support \u00b7 catalyst \u00b7 fundamentals \u00b7 politicians",why:"Support+fund confirm \u00b7 pol sell=1",athdip:null,support:78.7,catalyst:59.5,fund:74.9,pol:48.7,trump:null,rsi4h:null,sector:"Technology",pe:40.5,peg:0.9,fcfy:0.8,roe:41.1},
  {kind:"single",ticker:"AFL",price:114.89,tags:"support \u00b7 catalyst \u00b7 fundamentals \u00b7 politicians",why:"Top support score today",athdip:null,support:86.8,catalyst:61.5,fund:66.0,pol:46.9,trump:null,rsi4h:null,sector:"Financial Services",pe:12.4,peg:1.18,fcfy:8.9,roe:16.9},
  {kind:"single",ticker:"ADM",price:85.85,tags:"catalyst",why:"Top catalyst score today",athdip:null,support:null,catalyst:77.1,fund:null,pol:null,trump:null,rsi4h:null,sector:"",pe:23.5,peg:1.05,fcfy:2.8,roe:7.6},
  {kind:"single",ticker:"BA",price:211.21,tags:"support \u00b7 politicians \u00b7 trump",why:"Top Trump tracker \u00b7 pol sells=2",athdip:null,support:53.0,catalyst:null,fund:null,pol:42.1,trump:100.0,rsi4h:null,sector:"",pe:74.9,peg:1.53,fcfy:3.4,roe:173.5},
  {kind:"single",ticker:"CHWY",price:20.7,tags:"politicians",why:"Top politicians \u00b7 buys=4 sells=0",athdip:null,support:null,catalyst:null,fund:null,pol:62.5,trump:null,rsi4h:null,sector:"",pe:34.5,peg:0.47,fcfy:5.5,roe:63.8}
];

const ATHDIP = [
  {ticker:"AMGN",price:391.27,ath:447.03,pctAth:-12.47,days:10,rsi4h:23.5,rsiD:36.7,score:52.09},
  {ticker:"LLY",price:1130.03,ath:1292.65,pctAth:-12.58,days:14,rsi4h:28.0,rsiD:38.7,score:42.74}
];

const BACKTEST_YTD = [
  {mode:"trump*",ret:60.68,excess:47.97,win:58.3,dd:-11.8,avg:10.0},
  {mode:"athdip\u2020",ret:39.57,excess:26.85,win:22.4,dd:-11.56,avg:0.7},
  {mode:"catalyst",ret:16.5,excess:3.79,win:50.0,dd:-7.23,avg:9.0},
  {mode:"support",ret:16.1,excess:3.39,win:52.8,dd:-7.58,avg:10.0},
  {mode:"value",ret:1.36,excess:-11.35,win:61.1,dd:-16.7,avg:7.0},
  {mode:"SPY",ret:12.71,excess:0.0,win:0.0,dd:0.0,avg:1.0}
];

const TRUMP_SOURCES = [
  { label: "Truth Social", count: 80 },
  { label: "Google News", count: 232 },
  { label: "White House", count: 60 },
];

const TRUMP = [
  {ticker:"BA",score:100.0,mentions:63,themes:"defense, tariffs_trade",sources:"news, truth, WH"},
  {ticker:"INTC",score:81.59,mentions:76,themes:"company, govt_equity, semis_tech",sources:"news, truth, WH"},
  {ticker:"AAPL",score:79.25,mentions:51,themes:"china, company, tariffs_trade",sources:"news, truth, WH"},
  {ticker:"XLI",score:76.18,mentions:40,themes:"immigration_labor, tariffs_trade",sources:"news, truth, WH"},
  {ticker:"CAT",score:76.18,mentions:40,themes:"immigration_labor, tariffs_trade",sources:"news, truth, WH"},
  {ticker:"DE",score:76.18,mentions:40,themes:"immigration_labor, tariffs_trade",sources:"news, truth, WH"},
  {ticker:"LMT",score:74.26,mentions:53,themes:"defense, govt_equity",sources:"news, truth, WH"},
  {ticker:"GM",score:73.29,mentions:37,themes:"auto, energy_green, tariffs_trade",sources:"news, truth, WH"},
  {ticker:"F",score:73.29,mentions:37,themes:"auto, energy_green, tariffs_trade",sources:"news, truth, WH"},
  {ticker:"NKE",score:72.54,mentions:35,themes:"tariffs_trade",sources:"news, truth, WH"}
];

const SUPPORT = [
  {ticker:"AFL",price:114.89,rsi:37.27,rsiBias:"toward oversold",rsiSlope:-10.08,prox:0.003,pct52h:-11.32,peg:1.18,fcfy:0.0894,roe:0.169,score:86.81},
  {ticker:"UNH",price:390.89,rsi:42.64,rsiBias:"toward oversold",rsiSlope:-7.2,prox:0.091,pct52h:-15.32,peg:1.079,fcfy:0.0695,roe:0.142,score:79.92},
  {ticker:"AMAT",price:469.87,rsi:44.7,rsiBias:"toward overbought",rsiSlope:11.67,prox:0.14,pct52h:-36.41,peg:0.904,fcfy:0.0083,roe:0.411,score:78.69},
  {ticker:"ADI",price:364.05,rsi:45.0,rsiBias:"toward overbought",rsiSlope:6.96,prox:0.166,pct52h:-18.11,peg:0.541,fcfy:0.0235,roe:0.122,score:78.03},
  {ticker:"BALL",price:60.34,rsi:35.92,rsiBias:"toward oversold",rsiSlope:-14.75,prox:0.33,pct52h:-10.77,peg:1.056,fcfy:0.0238,roe:0.172,score:75.74},
  {ticker:"AON",price:311.07,rsi:30.2,rsiBias:"toward oversold",rsiSlope:-6.77,prox:0.0,pct52h:-18.46,peg:2.435,fcfy:0.0484,roe:0.447,score:74.29},
  {ticker:"AME",price:235.88,rsi:42.72,rsiBias:"toward overbought",rsiSlope:3.16,prox:0.27,pct52h:-9.68,peg:2.701,fcfy:0.0276,roe:0.146,score:74.22},
  {ticker:"AEE",price:107.09,rsi:49.6,rsiBias:"toward overbought",rsiSlope:8.35,prox:0.226,pct52h:-8.85,peg:2.631,fcfy:-0.0603,roe:0.119,score:74.13}
];

const CATALYST = [
  {ticker:"ADM",price:85.85,rsi:63.77,rsiBias:"toward overbought",rsiSlope:3.56,day:1.6,vol:0.06,pct52h:-2.33,score:77.08},
  {ticker:"BBY",price:90.14,rsi:59.54,rsiBias:"toward overbought",rsiSlope:3.68,day:0.91,vol:0.06,pct52h:-1.23,score:76.48},
  {ticker:"AWK",price:141.33,rsi:62.24,rsiBias:"neutral",rsiSlope:0.44,day:0.68,vol:0.04,pct52h:-0.66,score:76.27},
  {ticker:"XOM",price:164.68,rsi:60.01,rsiBias:"toward overbought",rsiSlope:2.86,day:2.5,vol:0.09,pct52h:-5.41,score:73.67},
  {ticker:"BEN",price:34.69,rsi:56.59,rsiBias:"toward overbought",rsiSlope:10.01,day:0.1,vol:0.03,pct52h:-4.4,score:71.8},
  {ticker:"CRM",price:252.37,rsi:68.83,rsiBias:"toward oversold",rsiSlope:-13.06,day:1.3,vol:0.05,pct52h:-5.93,score:69.82},
  {ticker:"AIZ",price:281.01,rsi:48.35,rsiBias:"toward oversold",rsiSlope:-5.15,day:-1.66,vol:0.86,pct52h:-7.26,score:67.36},
  {ticker:"AMP",price:549.1,rsi:48.77,rsiBias:"toward oversold",rsiSlope:-10.72,day:-1.36,vol:0.11,pct52h:-4.1,score:67.18}
];

const POLITICIANS = [
  {ticker:"CHWY",score:62.49,buys:4,sells:0,filedAfter:25.0,pols:"Ro Khanna",sources:"capitoltrades"},
  {ticker:"MRVL",score:62.4,buys:5,sells:0,filedAfter:35.2,pols:"Gil Cisneros, Gilbert Cisneros, Ro Khanna",sources:"capitoltrades,house"},
  {ticker:"EME",score:60.37,buys:3,sells:0,filedAfter:23.7,pols:"Ro Khanna",sources:"capitoltrades"},
  {ticker:"LEN",score:59.99,buys:3,sells:0,filedAfter:22.7,pols:"Ro Khanna",sources:"capitoltrades"},
  {ticker:"MCHP",score:59.91,buys:3,sells:0,filedAfter:27.3,pols:"Ro Khanna",sources:"capitoltrades"},
  {ticker:"COO",score:59.73,buys:2,sells:0,filedAfter:5.5,pols:"Ro Khanna",sources:"capitoltrades"},
  {ticker:"GOOGL",score:58.21,buys:3,sells:1,filedAfter:21.0,pols:"David J. Taylor, Ro Khanna, Thomas H. Kean",sources:"capitoltrades,house"},
  {ticker:"CHTR",score:57.5,buys:2,sells:0,filedAfter:18.0,pols:"Ro Khanna",sources:"capitoltrades"}
];

const FUNDAMENTALS = [
  {ticker:"APP",sector:"Communication Serv",peg:0.69,fcfy:0.0307,roe:0.02,score:77.71},
  {ticker:"AVGO",sector:"Technology",peg:0.35,fcfy:0.0177,roe:0.442,score:77.71},
  {ticker:"AMAT",sector:"Technology",peg:0.9,fcfy:0.0083,roe:0.411,score:74.86},
  {ticker:"ADI",sector:"Technology",peg:0.54,fcfy:0.0235,roe:0.122,score:73.08},
  {ticker:"LLY",sector:"Healthcare",peg:1.11,fcfy:0.011,roe:1.023,score:72.04},
  {ticker:"BRK-B",sector:"Financial Services",peg:10.06,fcfy:0.067,roe:0.121,score:70.1},
  {ticker:"AMZN",sector:"Consumer Cyclical",peg:1.51,fcfy:0.0012,roe:0.306,score:69.74},
  {ticker:"AXP",sector:"Financial Services",peg:1.32,fcfy:null,roe:0.344,score:66.75}
];

function biasTone(bias: string): "success" | "warning" | "danger" | "info" | "neutral" {
  if (bias === "oversold" || bias === "toward oversold") return "success";
  if (bias === "overbought" || bias === "toward overbought") return "warning";
  return "neutral";
}

function focusTone(kind: string): "success" | "warning" | "danger" | "info" | "neutral" {
  if (kind === "conflict") return "danger";
  if (kind === "intersection" || kind === "confirm" || kind === "athdip") return "success";
  if (kind === "single") return "info";
  return "neutral";
}

function dash(n: number | null | undefined, digits = 1): string {
  if (n === null || n === undefined || Number.isNaN(n)) return "—";
  return n.toFixed(digits);
}

function polTone(buys: number, sells: number): "success" | "warning" | "danger" | "info" | "neutral" {
  if (buys > sells) return "success";
  if (sells > buys) return "warning";
  return "neutral";
}

function trumpTone(score: number): "success" | "warning" | "info" | "neutral" {
  if (score >= 85) return "success";
  if (score >= 70) return "info";
  return "neutral";
}

function formatBias(bias: string, slope: number): string {
  const arrow = slope < -2 ? " ↓" : slope > 2 ? " ↑" : "";
  return `${bias}${arrow}`;
}

function pct(x: number): string {
  return `${(x * 100).toFixed(1)}%`;
}

/** Native browser tooltip on column headers (hover). */
function th(label: string, tip: string) {
  return <span title={tip}>{label}</span>;
}

export default function ScreenDashboard() {
  const srcTotal = TRUMP_SOURCES.reduce((a, s) => a + s.count, 0);
  const cross = FOCUS.filter((r) => r.kind !== "single");
  const singles = FOCUS.filter((r) => r.kind === "single");

  const crossHeaders = [
    th(
      "Kind",
      "Row type: conflict means modes disagree; intersection means modes agree; athdip or confirm means setup-driven signals",
    ),
    th("Ticker", "Stock ticker symbol"),
    th(
      "Price",
      "Latest screen price (usually prior session close or last available quote)",
    ),
    th("Why", "Reason this name was selected for the Today list"),
    th("Modes", "Which screener modes tagged this ticker"),
    th(
      "Ath",
      "Athdip-mode composite score (higher means deeper four-hour relative strength index and a fresher all-time-high setup)",
    ),
    th("Sup", "Support-mode composite score"),
    th("Cat", "Catalyst-mode composite score"),
    th("Fund", "Fundamentals-mode composite score"),
    th(
      "Pol",
      "Politicians-mode score based on freshness-weighted United States Congress trading flow",
    ),
    th("Trump", "Trump-tracker theme score from Truth Social, news, and White House feeds"),
    th("Sector", "Company sector classification from Yahoo Finance"),
    th("PE", "Trailing price-to-earnings ratio"),
    th(
      "PEG",
      "Price/earnings-to-growth ratio (lower often means cheaper relative to expected growth)",
    ),
    th("FCF%", "Free-cash-flow yield as a percent of market value"),
    th("ROE%", "Return on equity as a percent"),
  ];
  const singleHeaders = [
    th("Mode", "Primary single-mode leader category"),
    th("Ticker", "Stock ticker symbol"),
    th(
      "Price",
      "Latest screen price (usually prior session close or last available quote)",
    ),
    th("Why", "Reason this name is listed as a single-mode leader"),
    th("Lead", "Composite or mode score in the leading category"),
    th("Sector", "Company sector classification from Yahoo Finance"),
    th("PE", "Trailing price-to-earnings ratio"),
    th("PEG", "Price/earnings-to-growth ratio"),
    th("FCF%", "Free-cash-flow yield as a percent of market value"),
    th("ROE%", "Return on equity as a percent"),
  ];

  return (
    <Stack gap={28} style={{ maxWidth: 1100 }}>
      <Stack gap={8}>
        <H1>Screener dashboard</H1>
        <Text tone="secondary">
          All modes · SP500/{RUN.universe} · {RUN.asOf}
        </Text>
      </Stack>

      <Grid columns={4} gap={12}>
        <Stat value={RUN.vix.toFixed(1)} label="VIX" />
        <Stat value={RUN.regime} label="Regime" tone="info" />
        <Stat value={String(RUN.cape)} label="CAPE" tone="warning" />
        <Stat value={`${RUN.buffett}%`} label="Buffett · expensive" tone="warning" />
      </Grid>

      <Grid columns={6} gap={10}>
        <Stat value={String(RUN.support)} label="Support" />
        <Stat value={String(RUN.catalyst)} label="Catalyst" />
        <Stat value={String(RUN.fund)} label="Fundamentals" />
        <Stat value={String(RUN.pol)} label="Politicians" />
        <Stat value={String(RUN.trumpTickers)} label="Trump" tone="info" />
        <Stat value={String(RUN.athdipPass)} label="Athdip" tone="success" />
      </Grid>

      <Callout tone="info" title={RUN.note}>
        Rebuild: python3 scripts/build_screen_dashboard.py
      </Callout>

      <Stack gap={10}>
        <Row align="center" gap={10}>
          <H2>Today</H2>
          <Pill tone="warning">watchlist · not advice</Pill>
        </Row>
        <Text tone="secondary">
          Intersections / conflicts first, then top single-mode leaders — with fundamentals.
        </Text>

        <Text weight="semibold">Cross-mode intersections & conflicts</Text>
        <Table
          headers={crossHeaders}
          columnAlign={["left","left","right","left","left","right","right","right","right","right","right","left","right","right","right","right"]}
          rows={cross.map((r) => [
            r.kind,
            r.ticker,
            dash(r.price, 2),
            r.why,
            r.tags,
            dash(r.athdip),
            dash(r.support),
            dash(r.catalyst),
            dash(r.fund),
            dash(r.pol),
            dash(r.trump),
            r.sector || "—",
            dash(r.pe),
            dash(r.peg, 2),
            dash(r.fcfy),
            dash(r.roe),
          ])}
          rowTone={cross.map((r) => focusTone(r.kind))}
        />

        <Text weight="semibold">Single-mode leaders</Text>
        <Table
          headers={singleHeaders}
          columnAlign={["left","left","right","left","right","left","right","right","right","right"]}
          rows={singles.map((r) => {
            const lead = r.support ?? r.catalyst ?? r.trump ?? r.pol ?? r.fund ?? null;
            return [
              r.tags.split(" · ")[0] || r.tags,
              r.ticker,
              dash(r.price, 2),
              r.why,
              dash(lead),
              r.sector || "—",
              dash(r.pe),
              dash(r.peg, 2),
              dash(r.fcfy),
              dash(r.roe),
            ];
          })}
          rowTone={singles.map((r) => focusTone(r.kind))}
        />
        <Text tone="secondary" style={{ fontSize: 12 }}>
          Source: output/today_focus.csv · {RUN.asOf}
        </Text>
      </Stack>

      <Divider />

      <Stack gap={10}>
        <Row align="center" gap={10}>
          <H2>Athdip</H2>
          <Pill tone="success">ATH setup + 4h RSI dip</Pill>
        </Row>
        <Table
          headers={["Ticker","Price","ATH","%ATH","Days","RSI 4h","RSI D","Score"]}
          columnAlign={["left","right","right","right","right","right","right","right"]}
          rows={ATHDIP.map((r) => [
            r.ticker,
            dash(r.price, 2),
            dash(r.ath, 2),
            `${dash(r.pctAth)}%`,
            String(r.days),
            dash(r.rsi4h),
            dash(r.rsiD),
            dash(r.score),
          ])}
        />
      </Stack>

      <Divider />

      <Stack gap={10}>
        <Row align="center" gap={10}>
          <H2>Trump tracker</H2>
          <Pill tone="warning">policy / themes</Pill>
        </Row>
        <UsageBar
          total={srcTotal || 1}
          segments={TRUMP_SOURCES.map((s) => ({ id: s.label, value: s.count }))}
          topLeftLabel="Feed mix"
          topRightLabel={`${srcTotal} items`}
        />
        <BarChart
          categories={TRUMP.slice(0, 10).map((r) => r.ticker)}
          series={[{ name: "Trump score", data: TRUMP.slice(0, 10).map((r) => r.score), tone: "warning" }]}
          height={200}
        />
        <Table
          headers={["Ticker","Score","Mentions","Themes"]}
          columnAlign={["left","right","right","left"]}
          rows={TRUMP.map((r) => [r.ticker, dash(r.score), String(r.mentions), r.themes])}
          rowTone={TRUMP.map((r) => trumpTone(r.score))}
        />
      </Stack>

      <Divider />

      <Stack gap={10}>
        <H2>YTD backtest</H2>
        <BarChart
          categories={BACKTEST_YTD.map((r) => r.mode)}
          series={[{ name: "YTD return %", data: BACKTEST_YTD.map((r) => r.ret), tone: "info" }]}
          height={200}
        />
        <Table
          headers={["Mode","Return %","Excess %","Win %","Max DD %","Avg #"]}
          columnAlign={["left","right","right","right","right","right"]}
          rows={BACKTEST_YTD.map((r) => [
            r.mode,
            dash(r.ret, 2),
            dash(r.excess, 2),
            dash(r.win, 1),
            dash(r.dd, 2),
            dash(r.avg, 1),
          ])}
        />
      </Stack>

      <Divider />

      <Stack gap={10}>
        <H2>Politicians</H2>
        <Table
          headers={["Ticker","Score","Buys","Sells","Filed after","Politicians"]}
          columnAlign={["left","right","right","right","right","left"]}
          rows={POLITICIANS.map((r) => [
            r.ticker,
            dash(r.score),
            String(r.buys),
            String(r.sells),
            dash(r.filedAfter),
            r.pols,
          ])}
          rowTone={POLITICIANS.map((r) => polTone(r.buys, r.sells))}
        />
      </Stack>

      <Divider />

      <Stack gap={10}>
        <H2>Support</H2>
        <Table
          headers={["Ticker","Price","RSI","Bias","Prox","%52wH","PEG","FCF","ROE","Score"]}
          columnAlign={["left","right","right","left","right","right","right","right","right","right"]}
          rows={SUPPORT.map((r) => [
            r.ticker,
            dash(r.price, 2),
            dash(r.rsi),
            formatBias(r.rsiBias, r.rsiSlope ?? 0),
            dash(r.prox, 3),
            `${dash(r.pct52h)}%`,
            dash(r.peg, 2),
            r.fcfy == null ? "—" : pct(r.fcfy),
            r.roe == null ? "—" : pct(r.roe),
            dash(r.score, 2),
          ])}
          rowTone={SUPPORT.map((r) => biasTone(r.rsiBias))}
        />
      </Stack>

      <Divider />

      <Stack gap={10}>
        <H2>Catalyst</H2>
        <Table
          headers={["Ticker","Price","RSI","Bias","Day %","Vol×","%52wH","Score"]}
          columnAlign={["left","right","right","left","right","right","right","right"]}
          rows={CATALYST.map((r) => [
            r.ticker,
            dash(r.price, 2),
            dash(r.rsi),
            formatBias(r.rsiBias, r.rsiSlope ?? 0),
            dash(r.day, 2),
            dash(r.vol, 2),
            `${dash(r.pct52h)}%`,
            dash(r.score, 2),
          ])}
          rowTone={CATALYST.map((r) => biasTone(r.rsiBias))}
        />
      </Stack>

      <Divider />

      <Stack gap={10}>
        <H2>Fundamentals</H2>
        <Table
          headers={["Ticker","Sector","PEG","FCF yld","ROE","Score"]}
          columnAlign={["left","left","right","right","right","right"]}
          rows={FUNDAMENTALS.map((r) => [
            r.ticker,
            r.sector,
            dash(r.peg, 2),
            r.fcfy == null ? "—" : pct(r.fcfy),
            r.roe == null ? "—" : pct(r.roe),
            dash(r.score, 2),
          ])}
        />
      </Stack>

      <Card>
        <CardHeader>Reproduce</CardHeader>
        <CardBody>
          <Stack gap={6}>
            <Text style={{ fontFamily: "monospace", fontSize: 12 }}>
              stock-screener --mode all --universe sp500 --limit 80 --no-reddit --no-grok --no-trump-x
            </Text>
            <Text style={{ fontFamily: "monospace", fontSize: 12 }}>
              python3 scripts/build_screen_dashboard.py
            </Text>
            <Spacer height={4} />
            <Text tone="secondary" style={{ fontSize: 13 }}>
              Project skill: .cursor/skills/daily-screen
            </Text>
          </Stack>
        </CardBody>
      </Card>
    </Stack>
  );
}
